site_name: 'Credibanco App Angular'
site_description: 'Aplicación frontend desarrollada en Angular'

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Components: components.md
  - API Integration: api.md
  - Deployment: deployment.md
  - Development: development.md

plugins:
  - techdocs-core
  - search

theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

repo_url: https://github.com/giovanemere/credibanco-app-angular
edit_uri: edit/main/docs/

extra:
  version:
    provider: mike
  generator: false
